parameters:

    #
    # Parameters
    #
    gearman.cache.id: gearman.workers

    #
    # Generators
    #
    gearman.unique_job_identifier.class: Mmoreram\GearmanBundle\Generator\UniqueJobIdentifierGenerator

    #
    # Dispatchers
    #
    gearman.dispatcher.callbacks.class: Mmoreram\GearmanBundle\Dispatcher\GearmanCallbacksDispatcher

    #
    # Services
    #
    gearman.client.class:           Mmoreram\GearmanBundle\Service\GearmanClient
    gearman.callbacks.class:        Mmoreram\GearmanBundle\Service\GearmanCallbacks
    gearman.execute.class:          Mmoreram\GearmanBundle\Service\GearmanExecute
    gearman.describer.class:        Mmoreram\GearmanBundle\Service\GearmanDescriber
    gearman.parser.class:  Mmoreram\GearmanBundle\Service\GearmanParser
    gearman.cache.wrapper.class: Mmoreram\GearmanBundle\Service\GearmanCacheWrapper

    #
    # EventListeners
    #
    gearman.swiftmailer_email_sender.listener.class: Mmoreram\GearmanBundle\EventListener\SwiftmailerEmailSenderListener

    #
    # Commands
    #
    gearman.command.cache_clear.class: Mmoreram\GearmanBundle\Command\GearmanCacheClearCommand
    gearman.command.cache_warmup.class: Mmoreram\GearmanBundle\Command\GearmanCacheWarmupCommand
    gearman.command.job_describe.class: Mmoreram\GearmanBundle\Command\GearmanJobDescribeCommand
    gearman.command.job_execute.class: Mmoreram\GearmanBundle\Command\GearmanJobExecuteCommand
    gearman.command.worker_describe.class: Mmoreram\GearmanBundle\Command\GearmanWorkerDescribeCommand
    gearman.command.worker_execute.class: Mmoreram\GearmanBundle\Command\GearmanWorkerExecuteCommand
    gearman.command.worker_list.class: Mmoreram\GearmanBundle\Command\GearmanWorkerListCommand

    #
    # Externals
    #
    gearman.external.symfony_finder.class:  Symfony\Component\Finder\Finder
