imports:
    - php

filter:
    excluded_paths: [vendor/*, Tests/*, Resources/*]

tools:
    php_mess_detector: true
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor, Tests]
    external_code_coverage:
        timeout: 600    # Timeout in seconds.